services:
  db:
    image: postgres:15-alpine
    container_name: desafio_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mudarsenha123
      POSTGRES_DB: desafio_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_novo:/var/lib/postgresql/data
    networks:
      - desafio_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: desafio_backend
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mudarsenha123
      DATABASE_NAME: desafio_db
      JWT_SECRET: super_secret_jwt_key_troque_em_producao
      JWT_EXPIRES_IN: 7d
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - desafio_net
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: desafio_frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - desafio_net

volumes:
  pgdata_novo:
  uploads_data:

networks:
  desafio_net: